# Hy guys, I am back with my new model which is used for salary detection in industry on the basis of the industry pattern. 26-05-2021

In [1]:
import pandas  #import the historical data

In [4]:
db=pandas.read_csv("SalaryData.csv")  # read the whole data file by the help of the pandas function read_csv

In [43]:
db.info  # info tells about all the information of the matter

<bound method DataFrame.info of     YearsExperience    Salary
0               1.1   39343.0
1               1.3   46205.0
2               1.5   37731.0
3               2.0   43525.0
4               2.2   39891.0
5               2.9   56642.0
6               3.0   60150.0
7               3.2   54445.0
8               3.2   64445.0
9               3.7   57189.0
10              3.9   63218.0
11              4.0   55794.0
12              4.0   56957.0
13              4.1   57081.0
14              4.5   61111.0
15              4.9   67938.0
16              5.1   66029.0
17              5.3   83088.0
18              5.9   81363.0
19              6.0   93940.0
20              6.8   91738.0
21              7.1   98273.0
22              7.9  101302.0
23              8.2  113812.0
24              8.7  109431.0
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0>

In [28]:
db.columns   # It helps you to tell the column heading and datatype

Index(['YearsExperience', 'Salary'], dtype='object')

In [36]:
x=db['YearsExperience'].values.reshape(30,1)  # we can also use the .values because we will work on the numpy data and 
                                              # it will reshape to convert 1D to 2D data.

In [17]:
x  # input of the data to train the model ( also it is a indepent and known as feature)

array([[ 1.1],
       [ 1.3],
       [ 1.5],
       [ 2. ],
       [ 2.2],
       [ 2.9],
       [ 3. ],
       [ 3.2],
       [ 3.2],
       [ 3.7],
       [ 3.9],
       [ 4. ],
       [ 4. ],
       [ 4.1],
       [ 4.5],
       [ 4.9],
       [ 5.1],
       [ 5.3],
       [ 5.9],
       [ 6. ],
       [ 6.8],
       [ 7.1],
       [ 7.9],
       [ 8.2],
       [ 8.7],
       [ 9. ],
       [ 9.5],
       [ 9.6],
       [10.3],
       [10.5]])

In [8]:
y=db['Salary']

In [9]:
y              # It is the output which we will require when we predict 

0      39343.0
1      46205.0
2      37731.0
3      43525.0
4      39891.0
5      56642.0
6      60150.0
7      54445.0
8      64445.0
9      57189.0
10     63218.0
11     55794.0
12     56957.0
13     57081.0
14     61111.0
15     67938.0
16     66029.0
17     83088.0
18     81363.0
19     93940.0
20     91738.0
21     98273.0
22    101302.0
23    113812.0
24    109431.0
25    105582.0
26    116969.0
27    112635.0
28    122391.0
29    121872.0
Name: Salary, dtype: float64

In [19]:
from sklearn.linear_model import LinearRegression   # LinearRegression is the algo which is used to train the model 

In [20]:
mind=LinearRegression()    # It helps to create the empty mind 

In [21]:
mind.fit(x,y)              # fit function helps you to train the model by step by step and sets the weight and bias also 

LinearRegression()

In [32]:
import joblib              # joblib is the module in which lots of function like dump to dump the trained model file 

In [35]:
joblib.dump(mind,'trained.sk1') # dump the trained model file saved. This process helps to not trained again and again the model

['trained.sk1']

In [23]:
mind.coef_                    # mind.coef_ helps to tell the weight of the trained model 

array([9449.96232146])

In [24]:
mind.intercept_                # mind.intercept_ helps to tell the bias of the trained model 

25792.200198668717

In [25]:
mind.predict([[1.1]])          # mind.predict helps you to predict the newly data 

array([36187.15875227])

In [39]:
# how to solve the accuray of the model 
# 1) predictor data 
# 2) actual data 

# Formule  accurary = ( predicted value (y) / actual value (y) ) * 100
( 36187.15875227 / 39343.0 ) * 100
 

91.97864614358335

In [41]:
# Our model accurary = 91.97 %    # if the accurary of our model is larger then 90 % or nearly to 90% then its nice model 

In [ ]:
#THANKS CREATERS TO MOTIVATE ME  
   # VISHU GOYAL FELL FREE TO ASK DOUBT ANYTIME
      # 7453010168 DM ME ON WHATSAPP